name: CI

# Runs build and test on:
#   every push to main that has a change in a file not in the docs folder
#   every pull request with main branch as the base that has a change in a file not in the docs folder
on:
  push:
    branches:
      - main
    paths:
      - '**'
      - '!README.md'
  pull_request:
    branches:
      - main
    paths:
      - '**'
      - '!README.md'

jobs:
  test:
    name: CI Checks for Node
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Installation
        run: npm ci

      - name: Unit Tests
        run: npm run test

      - name: Unit Tests for Next versions
        run: npm run test:next

      - name: TypeCheck and Build
        run: npm run build
